### ISSUE TITLE
double check for v10

### ISSUE THREAD

**Issue by edspark** [sparkfun/Micro_Bit_Weather_Bit#2]
None of the changes I made yesterday got pushed up. I'm not sure why. On my home machine it says it was pushed. I've updated 1, 2, 4, and 5. The TX/RX lines are programmable in microbit. So it doesn't matter. There isn't a set I/O for those. 

Sorry that you went through the checklist on old junk. 

1) Is the version number correct? [NO]
comment: Needs to be changed to v10

2) Is the version number included on all sheets? [NO]
comment: Make sure to change revision on both pages

3) Are the TX/RX pins of the FTDI properly connected? [NO]
comment: I'm confused are the MOSI/MISO pins being used for TX/RX? If so have you confirmed that the polarity of the RX/TX lines are correct?

4) Is there a correct version number in the copper (aligned properly with the edge of the PCB)? [NO]
comment: Needs to be changed to v10

An airwire, you'll notice that the topside 3.3V line going into the resistor didn't quite make it all the way:

![airwire1](https://cloud.githubusercontent.com/assets/18684691/26640065/d6cb14aa-45e3-11e7-98ab-9fbe399f05c5.JPG)

**Comment by ToniCorinne** [comment]
@ADataDate can this issue be closed out? I'm assuming this was all addressed for the live version of the board.
