### ISSUE TITLE
weatherproof?

### ISSUE THREAD

**Issue by nielsswinkels** [sparkfun/Micro_Bit_Weather_Bit#3]
I can't imagine this thing to be able to survive outdoor conditions. What would be the best strategy to measure outdoor humidity with this?

On a side note I was wondering it if has any max & min temperatures it can handle?

**Comment by ADataDate** [comment]
The temp range is -40C to 85C.

I've actually seen some pretty inventive solutions for weatherproofing: https://twitter.com/thenerdyteacher/status/893254979515015168. This will, of course, skew temperature data but that is why the weatherproof DS18B20 Temp sensor connection port and makecode package is also available.  

I've also seen people take it to the beach screwed onto a pole stuck in the ground. I think your solution will depend on your environment. 

The weather:bit can also be placed in a project enclosure like the [Big Red Box](https://www.sparkfun.com/products/11366). Holes can be drilled for the weather meters and external temp sensor then sealed with epoxy or even hot glue. The [BME280](https://www.bosch-sensortec.com/bst/products/all_products/bme280) is meant to be put into an enclosure for wearable devices and such. So,  some experiments will probably need to be conducted to work with off-sets and get it properly calibrated.
